---
- name: Stop hardware information collect
  shell: /srv/flextrace/flextrace.sh -f
  args:
    executable: /bin/bash
  register: stophwcollect

- name: copy hardware information
  when: stophwcollect|success
  synchronize: src=/srv/flextrace/*.gz dest=/tmp/ mode=pull
