---
- name: Environment with httpd
  hosts: apache_web_server
  user: root
  become: yes
  roles:
    - common
    - httpd
    - static_content

- name: Environment with the benchmark
  hosts: benchmark
  user: root
  become: yes
  roles:
    - benchmark
