---
- name: Environment with httpd
  hosts: apache_web_server
  user: root
  become: yes
  roles:
    - common
    - increase_filedescriptor
    - httpd
    - static_content
    - python
    - dynamic_content
    - flextrace
    - mpm_configuration
