---
- name: Turn off apache
  service: name=apache2 state=stopped

- name: Install mod python
  apt: name=libapache2-mod-python update_cache=yes state=latest cache_valid_time=3600

- name: Enable python module
  shell: a2enmod python
  register: enabledmodules

- name: Started apache again
  when: enabledmodules|success
  service: name=apache2 state=started
