---
- package: update_cache=yes

- name: Install Apache utils
  package: name=apache2-utils

- name: Copy benchmark script
  synchronize: src=scripts dest=/srv/
  register: copiedscripts

- name: Setup results folder
  when: copiedscripts|success
  file: path=/srv/scripts/results state=directory mode=0755
