---
- package: update_cache=yes

- name: Install Apache utils
  package: name=apache2-utils

- name: Clone Stress scripts
  git: repo=https://github.com/LSS-USP/stress_scripts_web_server.git
       dest=/srv/scripts/ab/
       force=yes
  register: clonestressscripts

- name: Setup results folder
  when: clonestressscripts|success
  file: path=/srv/scripts/results state=directory mode=0755
